### ISSUE TITLE
What would be the process to train a new model to predict emojis on a different dataset? 

### ISSUE THREAD

**Issue by sersoage** [bfelbo/DeepMoji#2]

**Comment by bfelbo** [comment]
Why would you need to train a new model? Why not just use the pretrained model?

**Comment by sersoage** [comment]
Because i wanted to test on different languages, is it possible?

**Comment by bfelbo** [comment]
You would need a dataset with tweets in that language. Then you could freeze parts of the network and simply train with model.fit().

**Comment by sersoage** [comment]
Thanks!

**Comment by PeterPanUnderhill** [comment]
Sorry to ask in a closed question but if I have a dataset(with emoticons) in Chinese, I guess I need to start with building the vocabulary and then work out the embedding layer, right? I feel that I need to retrain the whole network instead of freezing parts of the network. Am I right? Thanks in advance.
